import AuthLayout from "@/app/(auth)/AuthLayout";
import "@/styles/globals.css";
import "@/styles/all.min.css";
import "@/styles/bootstrap.min.css";
import "@/styles/auth-style.css";
// import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <AuthLayout>
            {children}
        </AuthLayout>
        </body>
        </html>
    )
}
