import AuthLayout from "@/app/components/AuthLayout";
// import "@/app/styles/ks_bootstrap.css";
// import "@/app/styles/we-tax.css";
import "@/app/styles/globals.css";
import "@/app/styles/all.min.css";
import "@/app/styles/bootstrap.min.css";
import "@/app/styles/uf-style.css";
// import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <AuthLayout>
            {children}
        </AuthLayout>
        </body>
        </html>
    )
}
